- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/
    - MotU-Web:
        - abbr: MW
          href: https://motu.fritz.box/

- Social:
    - Reddit:
        - abbr: RDT
          href: https://reddit.com/

- Media:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
    - Watch2Gether:
        - abbr: W2G
          href: https://w2g.tv/
    - Joyn:
        - abbr: JY
          href: https://joyn.de

- Automation:
    - Open WebUI:
        - abbr: OI
          href: https://chat.fritz.box
    - n8n:
        - abbr: N8N
          href: https://n8n.fritz.box
