- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
    - MotU-Web:
        - abbr: MW
          href: https://motu.fritz.box/

- Social:
    - Reddit:
        - abbr: RDT
          href: https://reddit.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/reddit.png

- Media:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/youtube.png
    - Watch2Gether:
        - abbr: W2G
          href: https://w2g.tv/
    - Joyn:
        - abbr: JY
          href: https://joyn.de

- Automation:
    - Open WebUI:
        - abbr: OI
          href: https://chat.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-webui-light.png
    - n8n:
        - abbr: N8N
          href: https://n8n.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/n8n.png
