- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
    - Dashboardicons:
        - abbr: DI
          href: https://dashboardicons.com
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homarr.png
    - MotU-Web:
        - abbr: MW
          href: https://motu.fritz.box/

- Social:
    - Reddit:
        - abbr: RDT
          href: https://reddit.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/reddit.png

- Media:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/youtube.png
    - Watch2Gether:
        - abbr: W2G
          href: https://w2g.tv/
    - Joyn:
        - abbr: JY
          href: https://joyn.de

- Automation:
    - Open WebUI:
        - abbr: OI
          href: https://chat.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-webui-light.png
    - n8n:
        - abbr: N8N
          href: https://n8n.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/n8n.png

- Shopping:
    - Amazon:
        - abbr: AMZ
          href: https://amazon.de/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/amazon.png

- Gaming:
    - BoardGameArena:
        - abbr: BGA
          href: https://boardgamearena.com/
          icon: https://x.boardgamearena.net/data/themereleases/251222-1408/img/logo/logo_title_big.png
    - Melodice:
        - abbr: MEL
          href: https://melodice.com/
          icon: https://tse2.mm.bing.net/th/id/OIP.Kpn2jStgG0OUTqQ89JHeBgAAAA%3Fpid%3DApi
