---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

layout:
  Infrastructure:
    style: column

  IoT:
    style: column

  Documents:
    style: column

  Developer:
    style: row
    columns: 3

  Social:
    style: row
    columns: 3

  Media:
    style: row
    columns: 3

  Automation:
    style: row
    columns: 3
